on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - id: set-matrix
        run: |
          files=$(echo "{\"files\": [\"$(find script -type f | xargs | sed 's/ /", "/g')\"]}")
          echo "::set-output name=matrix::${files}"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  run:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    steps:
      - run: bash '${{matrix.file}}'
