on:
  push:
    branches:
    - master

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        word: [ "A", "B" ]
        verb: [ "say", "shout" ]
    steps:
      - run: "echo '${{matrix.verb}} ${{matrix.word}}'"
