on:
  push:
    branches:
    - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 1
       - id: set-matrix
         run: |
          #content=`cat ./matrix.json`
          #content="${content//'%'/'%25'}"
          #content="${content//$'\n'/'%0A'}"
          #content="${content//$'\r'/'%0D'}"
          #echo "::set-output name=matrix::$content"
          echo "::set-output name=matrix::[1,2,3]"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      
  run:
    needs: setup
    runs-on: ubuntu-latest
    #strategy:
    #  matrix: 
    steps:
      #- run: "echo '${{matrix.verb}} ${{matrix.word}}'"
      - run: "echo '${{ toJson(fromJSON(needs.setup.outputs.matrix)) }}'"
